apiVersion: v1
kind: ServiceAccount
metadata:
  name: podreaper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podreaper
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podreaper
subjects:
  - kind: Group
    name: manager
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: podreaper
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podreaper
  labels:
    app: podreaper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podreaper
  template:
    metadata:
      labels:
        app: podreaper
    spec:
      serviceAccountName: podreaper
      containers:
        - name: podreaper
          image: sgdan/pod-reaper:latest
          # for locally built image
          # image: podreaper:latest
          # imagePullPolicy: Never
          env:
            - name: ZONE_ID
              value: UTC
            - name: IGNORED_NAMESPACES
              value: kube-system,kube-public,kube-node-lease,podreaper,docker
            - name: CORS_ENABLED
              value: "false"
