version: "3.7"
services:
  gradle:
    image: gradle:5.6.3
    volumes:
      - .:/working
      - ~/.kube:/root/.kube
      - gradle_cache:/home/gradle/.gradle/caches
    working_dir: /working

volumes:
  gradle_cache:
